### ISSUE TITLE
Help to get it running

### ISSUE THREAD

**Issue by tordans** [wtimme/OSM-Completionist#12]
I have this query in my overpass window, the test-page shows results.

`natural=tree and ref!="" and type:node`

However, the Map UI does not highlight the trees.
Am I doing it wrong?

**Comment by wtimme** [comment]
Hey @tordans, thanks for testing the Overpass parser!

If I understood your query correctly, you are looking for all trees that have a `ref` tag set. From my understanding, the proper query would be

    natural=tree and ref=*

You can see example results [on overpass turbo][1]. Does that help?

[1]: https://overpass-turbo.eu/s/PnS

**Comment by tordans** [comment]
Thanks for the help. It's a bit different, it's "all trees that don't have a ref-tag (yet)".
Looks like the overpass turbo query is `natural=tree and ref is not null` (or `ref=*`).
I see the correct results in the preview now, but I still don't see the trees highlighted in the map view …!

**Comment by wtimme** [comment]
Glad to be of help! From my understanding,

> all trees that don't have a ref-tag (yet)

should translate into the query

    natural=tree and ref is null

When I enter this in the editor and go back to the map, I see the highlighted trees.

**Comment by tordans** [comment]
🤦‍♂  well, yes ;-D
