### ISSUE TITLE
Papercuts

### ISSUE THREAD

**Issue by tordans** [wtimme/OSM-Completionist#13]
For now, just a collection of quick nodes that are not really MVP-related

- #27 ~~The UI does not communicate that it is looking for overpass turbo _wizzard_ queries and overpass turbo queries will result in an error~~
- I wonder if the wizzard is powerfull enough in the long run for the queries I am thinking about
- #18 ~~Apparently there is an API for the user profile on osm.org which allows to store app specific data which is not used a lot, but Overpass might use it for its "save on osm.org". If so, this could be used to load the same queries in the app~~
- #24 ~~The preview-html-page could be centered to the current location~~

(I will update the list …)

**Comment by wtimme** [comment]
> The UI does not communicate that it is looking for overpass turbo wizzard queries and overpass turbo queries will result in an error

Yes, you're correct - at the moment, the UX could be very much improved.

I've gone ahead and changed the title to include "Wizard":

![overpass-query-wizard-title](https://user-images.githubusercontent.com/1681085/71755099-179c4e80-2e81-11ea-900e-b47cb2009ecb.png)

I've also added a "Help" button that opens the OSM wiki:

![overpass-query-wizard-wiki](https://user-images.githubusercontent.com/1681085/71755127-2d117880-2e81-11ea-913b-d08d1e71109f.png)

**Comment by wtimme** [comment]
> I wonder if the wizzard is powerfull enough in the long run for the queries I am thinking about

I hope so. ;) For now, it'll help to build a basic set of queries. 👍🏼

I'm closing the issue, since all feature requests/ideas have found their way into dedicated GitHub issues, or have already been implemented.
