### ISSUE TITLE
'Bug Reports & Suggestions' in Settings send an email to (probably) wrong address

### ISSUE THREAD

**Issue by habi** [wtimme/OSM-Completionist#33]
Tapping on the 'Bug Reports & Suggestions' item in the 'Settings' sends an email to [bryceco](https://github.com/bryceco), with the subject 'Completionist $VERSION feedback'.
I *think* this is the wrong address.

**Comment by LucasLarson** [comment]
I’m not sure if this is related, but in the App Store, the developer email listed is `no-spam-please` on `posteo.de`. Is that right?

**Comment by wtimme** [comment]
Thanks for your report, @habi! Yes, you're correct: Even though Bryce probably doesn't mind feedback, I think for this fork, it makes sense to change it to the address that @LucasLarson found (thanks for obfuscating it! 👍🏼).
