### ISSUE TITLE
Automatically update data (like presets.json) from iD when releasing a new version

### ISSUE THREAD

**Issue by wtimme** [wtimme/OSM-Completionist#34]
**Is your feature request related to a problem? Please describe.**
At the moment, the data from iD that our app incorporates is a bit dusted, since it used to be updated manually by hand. If we wanted to update them, it would require quite some manual work.

**Describe the solution you'd like**
When releasing a new version, the information from the iD repository (e. g. [presets.json][1]) should be copied into OSM-Completionist automatically.

**Describe alternatives you've considered**
We could continue to do this manually, but as pointed out, that requires time and effort.

**Additional context**
This was brought up in #32.

[1]: https://github.com/openstreetmap/iD/blob/master/data/presets/presets.json

**Comment by bryceco** [comment]
Note that often when the presets change it will also require code changes (sometimes significant) to support new functionality or to prevent the app from crashing.

**Comment by wtimme** [comment]
Thanks for raising this concern, Bryce!

Before implementing a mechanism to automatically update these JSON files from iD, I would like us to create integration tests first. When run, they should make sure that the JSON can be properly parsed and doesn't result in any errors.

**Comment by tordans** [comment]
Related: https://github.com/bryceco/GoMap/issues/119

**Comment by wtimme** [comment]
This is a good idea, but it should be implemented upstream, in [bryceco/GoMap](/bryceco/GoMap).
