### ISSUE TITLE
Compass UI broken?

### ISSUE THREAD

**Issue by tordans** [wtimme/OSM-Completionist#46]
I used the compass on a "Informationstafel".
It did update the number, but I did not show anything on the screen (the screen stayed blank).

Maybe a GoMap issue, maybe something with the new iOS or darkmode, maybe an issue in Completionist… – IDK.

![IMG_5124](https://user-images.githubusercontent.com/111561/72784204-971f7100-3c28-11ea-89eb-281bd259c03f.png)

**Comment by wtimme** [comment]
Thanks for the report! Yes, looks like an issue with Dark Mode.
