### ISSUE TITLE
OSM Completist doesn’t use the latest version of Go Map!!

### ISSUE THREAD

**Issue by TheAdventurer64** [wtimme/OSM-Completionist#73]

**Comment by wtimme** [comment]
Thanks for the report!

Yes, that is correct. Feel free to rebase/merge the `master` of GoMap!! and create a PR.

But beware: There are quite a lot of merge conflicts, which is why I haven‘t done that in a while.

**Comment by wtimme** [comment]
With the recent commits, I have added `project.yml` to the root directory of the repository. This is a project definition that can be used to automatically generate a Xcode project using XcodeGen, and it should allow this fork to be a bit more independent from GoMap when it comes to the project file.

I have also merged the latest version of GoMap into this fork.
